const DB_NAME='MinaPangutanaDB',STORE='questionBank',LEGACY_KEY='minapangutana_q_v1';
const sample=[
{questionBank:'Sample Bank',category:'Mining Methods',question:'Which mining method is commonly used for large, near-surface ore deposits?',optionA:'Open-pit mining',optionB:'Longwall mining',optionC:'Shrinkage stoping',optionD:'Block caving',correctAnswer:'A',explanation:'Open-pit mining is commonly suited to large deposits near the surface.'},
{questionBank:'Sample Bank',category:'Mineral Processing',question:'Which process reduces particle size by crushing and grinding?',optionA:'Flotation',optionB:'Comminution',optionC:'Leaching',optionD:'Smelting',correctAnswer:'B',explanation:'Comminution is size reduction by crushing and grinding.'},
{questionBank:'Sample Bank',category:'Mine Safety',question:'Which is generally the most effective level in the hierarchy of controls?',optionA:'PPE',optionB:'Administrative controls',optionC:'Elimination',optionD:'Warning signs',correctAnswer:'C',explanation:'Elimination removes the hazard itself.'}];
let qs=[],exam=[],ans={},i=0,cards=[],ci=0,flip=false;
const app=document.getElementById('app'),e=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function readBank(){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get('questions');r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function save(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(qs,'questions');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function init(){try{qs=await readBank()||JSON.parse(localStorage.getItem(LEGACY_KEY)||'null')||sample;await save();localStorage.removeItem(LEGACY_KEY)}catch(_){qs=sample}home()}
function sh(a){return [...a].sort(()=>Math.random()-.5)}
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function isStandalone(){return matchMedia('(display-mode:standalone)').matches||navigator.standalone===true}
function home(){const install=isIOS()&&!isStandalone()?'<div class="notice install-help"><b>Install on iPhone:</b> Open in Safari, tap Share, then “Add to Home Screen.”</div>':'';app.innerHTML=`<div class="hero"><h1>MinaPangutana</h1><b>MINING ENGINEERING REVIEWER</b><p class="muted">${qs.length} questions saved · Practice · Review · Master</p></div>${install}<div class="grid"><button onclick="setup()">Practice Exam</button><button onclick="flashSetup()">Flip Card Study</button><button class="secondary" onclick="bank()">Question Bank</button><button class="secondary" onclick="imports()">Import / Export</button></div><div class="card"><h3>About & Authorship</h3><p><b>Developed by Cristopher Gonzaga</b><br>Creator & Developer of MinaPangutana</p><p>© 2026 Cristopher Gonzaga. All rights reserved.</p><p class="muted">Independent educational reviewer. Not affiliated with, endorsed by, sponsored by, or an official application of the PRC, Board of Mining Engineering, or any government agency. User-imported and third-party materials remain the property of their respective owners.</p></div>`}
function setup(){if(!qs.length){alert('Import questions first.');return imports()}app.innerHTML=`<h2>Create Practice Exam</h2><div class="card"><label for="n">Number of questions</label><input id="n" inputmode="numeric" type="number" min="1" max="${qs.length}" value="${Math.min(25,qs.length)}"><button onclick="start()">START EXAM</button></div>`}
function start(){const n=Math.max(1,Math.min(qs.length,+document.getElementById('n').value||1));exam=sh(qs).slice(0,n);ans={};i=0;examView()}
function examView(){const q=exam[i];app.innerHTML=`<h2>Practice Exam ${i+1}/${exam.length}</h2><div class="card"><p class="muted">${e(q.category)} · ${e(q.questionBank)}</p><h3>${e(q.question)}</h3>${['A','B','C','D'].map(x=>`<button class="option ${ans[i]===x?'selected':''}" onclick="pick('${x}')"><b>${x}.</b> ${e(q['option'+x])}</button>`).join('')}</div><div class="grid"><button class="secondary" onclick="prev()">Previous</button>${i===exam.length-1?'<button onclick="submitExam()">SUBMIT</button>':'<button onclick="next()">Next</button>'}</div>`}
function pick(x){ans[i]=x;examView()}function prev(){if(i){i--;examView()}}function next(){if(i<exam.length-1){i++;examView()}}
function submitExam(){if(confirm(`Submit? ${exam.length-Object.keys(ans).length} unanswered.`))results()}
function results(){const n=exam.filter((q,j)=>ans[j]===q.correctAnswer).length;app.innerHTML=`<div class="hero"><h1>${n}/${exam.length}</h1><p>${Math.round(n/exam.length*100)}%</p></div><div class="grid"><button onclick="review()">Review Answers</button><button class="secondary" onclick="home()">Home</button></div>`}
function review(){app.innerHTML='<h2>Answer Review</h2>'+exam.map((q,j)=>{const ok=ans[j]===q.correctAnswer;return `<div class="card"><b class="${ok?'good':'bad'}">${j+1}. ${ok?'Correct':'Incorrect'}</b><p>${e(q.question)}</p><p>Your answer: ${e(ans[j]||'Unanswered')}<br>Correct: ${e(q.correctAnswer)}. ${e(q['option'+q.correctAnswer])}</p><p class="muted">${e(q.explanation)}</p></div>`}).join('')+'<button onclick="home()">HOME</button>'}
function flashSetup(){if(!qs.length){alert('Import questions first.');return imports()}app.innerHTML=`<h2>Flip Card Study</h2><div class="card"><label for="fn">Number of cards</label><input id="fn" inputmode="numeric" type="number" min="1" max="${qs.length}" value="${Math.min(25,qs.length)}"><button onclick="startFlash()">START</button></div>`}
function startFlash(){const n=Math.max(1,Math.min(qs.length,+document.getElementById('fn').value||1));cards=sh(qs).slice(0,n);ci=0;flip=false;flashView()}
function flashView(){const q=cards[ci];app.innerHTML=`<h2>Flip Card ${ci+1}/${cards.length}</h2><div class="card" onclick="flip=!flip;flashView()" style="min-height:330px;display:flex;flex-direction:column;justify-content:center;text-align:center">${flip?`<h3 class="good">${e(q.correctAnswer)}. ${e(q['option'+q.correctAnswer])}</h3><p>${e(q.explanation)}</p>`:`<h3>${e(q.question)}</h3><p>A. ${e(q.optionA)}<br>B. ${e(q.optionB)}<br>C. ${e(q.optionC)}<br>D. ${e(q.optionD)}</p><p class="muted">Tap to reveal answer</p>`}</div><div class="grid"><button class="secondary" onclick="if(ci){ci--;flip=false;flashView()}">Previous</button><button onclick="if(ci<cards.length-1){ci++;flip=false;flashView()}else home()">${ci<cards.length-1?'Next':'Finish'}</button></div>`}
function bank(){app.innerHTML=`<h2>Question Bank (${qs.length})</h2>`+qs.map((q,j)=>`<div class="card"><b>${j+1}. ${e(q.question)}</b><p class="muted">${e(q.questionBank)} · ${e(q.category)} · Answer ${e(q.correctAnswer)}</p></div>`).join('')+`<button class="secondary" onclick="clearBank()">CLEAR ALL</button>`}
async function clearBank(){if(confirm('Clear all questions?')){qs=[];await save();bank()}}
function imports(){app.innerHTML=`<h2>Import / Export</h2><div class="card"><p>Import MinaPangutana <b>.txt</b> safe-format files or <b>.json</b> question banks.</p><input id="file" type="file" accept=".txt,.json,text/plain,application/json" onchange="loadFile(this.files[0])"><textarea id="txt" placeholder="Or paste safe-format text or a JSON array here"></textarea><button onclick="doImport()">IMPORT QUESTIONS</button><button class="secondary" onclick="exportBank()">EXPORT JSON BACKUP</button></div>`}
async function loadFile(file){if(!file)return;document.getElementById('txt').value=await file.text()}
function normalizeQuestion(q){const answer=String(q.correctAnswer||'').trim().toUpperCase();if(!q.question||!q.optionA||!q.optionB||!q.optionC||!q.optionD||!['A','B','C','D'].includes(answer))return null;return{questionBank:q.questionBank||'Imported',category:q.category||'General',question:String(q.question).trim(),optionA:String(q.optionA).trim(),optionB:String(q.optionB).trim(),optionC:String(q.optionC).trim(),optionD:String(q.optionD).trim(),correctAnswer:answer,explanation:String(q.explanation||'').trim()}}
function parseSafe(text){const blocks=[...text.matchAll(/===\s*QUESTION\s+START\s*===\s*([\s\S]*?)\s*===\s*QUESTION\s+END\s*===/gi)];return blocks.map(m=>{const b=m[1],get=(name,next)=>{const r=new RegExp('\\[\\s*'+name+'\\s*\\]\\s*([\\s\\S]*?)(?=\\[\\s*(?:'+next+')\\s*\\]|$)','i').exec(b);return r?r[1].trim():''};const raw=get('ANSWER','EXPLANATION');return normalizeQuestion({questionBank:'Imported TXT',category:'Imported Questions',question:get('QUESTION','A|B|C|D|ANSWER|EXPLANATION').replace(/^\d+\s*[.)]\s*/,''),optionA:get('A','B|C|D|ANSWER|EXPLANATION'),optionB:get('B','C|D|ANSWER|EXPLANATION'),optionC:get('C','D|ANSWER|EXPLANATION'),optionD:get('D','ANSWER|EXPLANATION'),correctAnswer:(raw.match(/[A-D]/i)||[])[0],explanation:get('EXPLANATION','__END__')})}).filter(Boolean)}
async function doImport(){const text=document.getElementById('txt').value.trim();if(!text)return alert('Choose a file or paste questions first.');let incoming=[];try{const data=JSON.parse(text);if(Array.isArray(data))incoming=data.map(normalizeQuestion).filter(Boolean)}catch(_){incoming=parseSafe(text)}if(!incoming.length)return alert('No valid questions detected. Use MinaPangutana safe TXT format or JSON.');const existing=new Set(qs.map(q=>q.question.trim().toLowerCase()));const fresh=incoming.filter(q=>{const key=q.question.toLowerCase();if(existing.has(key))return false;existing.add(key);return true});qs.push(...fresh);await save();alert(`${fresh.length} imported. ${incoming.length-fresh.length} duplicate(s) skipped.`);home()}
function exportBank(){const b=new Blob([JSON.stringify(qs,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='MinaPangutana-question-bank.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
init();
